"""llama.cpp compatible completion request model."""
from pydantic import BaseModel, ConfigDict, Field
from typing import Optional, Union, List, Dict, Any


class LlamaCompletionRequest(BaseModel):
    """llama.cpp compatible completion request.

    Supports all parameters from llama.cpp server /completion endpoint.
    """
    model_config = ConfigDict(extra="allow")

    prompt: Union[str, List[str]] = Field(default="", description="Input prompt")
    max_tokens: Optional[int] = Field(default=-1, description="Maximum tokens to generate (-1 for unlimited)")
    n_predict: Optional[int] = Field(default=-1, description="Number of tokens to predict")
    max_new_tokens: Optional[int] = Field(default=-1, description="Maximum new tokens")
    temperature: Optional[float] = Field(default=0.8, ge=0.0, le=2.0, description="Sampling temperature")
    top_k: Optional[int] = Field(default=40, ge=0, description="Top-k sampling")
    top_p: Optional[float] = Field(default=0.95, ge=0.0, le=1.0, description="Top-p sampling")
    min_p: Optional[float] = Field(default=0.05, ge=0.0, le=1.0, description="Min-p sampling")
    typical_p: Optional[float] = Field(default=1.0, ge=0.0, le=1.0, description="Typical sampling")
    typical: Optional[float] = Field(default=1.0, ge=0.0, le=1.0, description="Typical (alias)")
    repeat_penalty: Optional[float] = Field(default=1.0, ge=0.0, le=2.0, description="Repetition penalty")
    repetition_penalty: Optional[float] = Field(default=1.0, ge=0.0, le=2.0, description="Repetition penalty (alias)")
    rep_pen: Optional[float] = Field(default=1.0, ge=0.0, le=2.0, description="Rep pen (alias)")
    repeat_last_n: Optional[int] = Field(default=64, ge=0, description="Last N tokens for repeat penalty")
    rep_pen_range: Optional[int] = Field(default=64, ge=0, description="Rep pen range")
    frequency_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0, description="Frequency penalty")
    presence_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0, description="Presence penalty")
    mirostat: Optional[int] = Field(default=0, ge=0, le=2, description="Mirostat mode")
    mirostat_mode: Optional[int] = Field(default=0, ge=0, le=2, description="Mirostat mode (alias)")
    mirostat_tau: Optional[float] = Field(default=5.0, ge=0.0, description="Mirostat tau")
    mirostat_eta: Optional[float] = Field(default=0.1, ge=0.0, description="Mirostat eta")
    tfs_z: Optional[float] = Field(default=1.0, ge=0.0, le=1.0, description="TFS-Z")
    tfs: Optional[float] = Field(default=1.0, ge=0.0, le=1.0, description="TFS (alias)")
    top_a: Optional[float] = Field(default=0.0, ge=0.0, description="Top-a sampling")
    seed: Optional[int] = Field(default=-1, description="Random seed (-1 for random)")
    stream: Optional[bool] = Field(default=False, description="Enable streaming")
    stop: Optional[Union[str, List[str]]] = Field(default=None, description="Stop sequences")
    stopping_strings: Optional[List[str]] = Field(default=None, description="Stop strings (alias)")
    ignore_eos: Optional[bool] = Field(default=False, description="Ignore EOS token")
    ban_eos_token: Optional[bool] = Field(default=False, description="Ban EOS token (alias)")
    n_keep: Optional[int] = Field(default=0, description="Number of tokens to keep")
    n_discard: Optional[int] = Field(default=0, description="Number of tokens to discard")
    n_probs: Optional[int] = Field(default=0, description="Number of probabilities")
    min_keep: Optional[int] = Field(default=0, description="Minimum keep")
    logit_bias: Optional[Union[Dict[str, float], List[Any]]] = Field(default=None, description="Logit bias (dict or list)")
    grammar: Optional[str] = Field(default=None, description="GBNF grammar")
    grammar_lazy: Optional[bool] = Field(default=False, description="Lazy grammar")
    cache_prompt: Optional[bool] = Field(default=False, description="Cache prompt")
    add_bos_token: Optional[bool] = Field(default=True, description="Add BOS token")
    skip_special_tokens: Optional[bool] = Field(default=True, description="Skip special tokens")
    samplers: Optional[List[str]] = Field(default=None, description="Samplers order")
    dry_multiplier: Optional[float] = Field(default=0.0, ge=0.0, description="DRY multiplier")
    dry_base: Optional[float] = Field(default=1.75, ge=1.0, description="DRY base")
    dry_allowed_length: Optional[int] = Field(default=2, ge=1, description="DRY allowed length")
    dry_penalty_last_n: Optional[int] = Field(default=-1, description="DRY penalty last N")
    dry_sequence_breakers: Optional[List[str]] = Field(default=None, description="DRY breakers")
    xtc_threshold: Optional[float] = Field(default=0.1, ge=0.0, le=0.5, description="XTC threshold")
    xtc_probability: Optional[float] = Field(default=0.0, ge=0.0, le=1.0, description="XTC probability")
    timings_per_token: Optional[bool] = Field(default=False, description="Include timings per token")
    post_sampling_probs: Optional[bool] = Field(default=False, description="Post sampling probs")
    id_slot: Optional[int] = Field(default=-1, description="Slot ID (-1 for auto)")
    model: Optional[str] = Field(default=None, description="Model name")
